@baseUrl = http://localhost:3000

GET {{baseUrl}}

###authLogin
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "a",
  "password": "a"
}

###readOneUser
# @name ReadOneUser
GET {{baseUrl}}/user/oi